### ISSUE TITLE
 ubuntu 22.04 Compilation error 

### ISSUE THREAD

**Issue by smokingfive** [Mastercard/pkcs11-tools#37] opened 2023-06-07 11:52 UTC
**Describe the bug**
When building pkcs-tools-2.5.1 package 2.5.1 I receive the following issue:

```
In file included from attribctx_lexer.c:49:
../gl/string.h:965:1: error: expected ',' or ';' before '_GL_ATTRIBUTE_MALLOC'
  965 | _GL_FUNCDECL_SYS (strdup, char *,
      | ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1657: libp11_la-attribctx_lexer.lo] Error 1
```
**To Reproduce**
1. Download pkcs11-tools-2.5.1.tar.gz
2. Untar the achive
3. ./configure
4. ./make

**Expected behavior**
Expect the package to build.

**Screenshots**

**Operating System (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 22.04

**Additional context**

**Comment by keldonin** [comment] 2023-06-07 13:00
Hi @smokingfive , this is actually a duplicate of #36. For some reasons, recent GCC versions interfere with flex & GNUlib, and I haven't found yet how to fix this. 

As a workaround, you can compile using clang. Check #36 for more details.

**Comment by keldonin** [comment] 2023-07-04 13:44
Issue solved and commited to the master branch. @smokingfive  if you have an opportunity to test, just do a fresh clone of the repo and try to build again.

**Closed** 2023-07-08 07:38 UTC
Labels: bug, duplicate
