### ISSUE TITLE
p11mkcert Make failed

### ISSUE THREAD

**Issue by thotheolh** [Mastercard/pkcs11-tools#27] opened 2021-03-24 08:14 UTC
I am getting the following errors when attempting to run `make` on the latest pkcs11-tools:

Making all in src
make[1]: Entering directory '/home/lm19/pkcs11-tools/src'
  CC       libcommon_la-version.lo
  CCLD     libcommon.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       p11mkcert.o
  CCLD     p11mkcert
../lib/.libs/libp11.a(libp11_la-pkcs11_ossl_eddsa_meth.o): In function `eddsa_method_setup':
/home/lm19/pkcs11-tools/lib/pkcs11_ossl_eddsa_meth.c:177: undefined reference to `EVP_PKEY_meth_get_digestsign'
/home/lm19/pkcs11-tools/lib/pkcs11_ossl_eddsa_meth.c:178: undefined reference to `EVP_PKEY_meth_set_digestsign'
collect2: error: ld returned 1 exit status
Makefile:1388: recipe for target 'p11mkcert' failed
make[1]: *** [p11mkcert] Error 1
make[1]: Leaving directory '/home/lm19/pkcs11-tools/src'
Makefile:1199: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by keldonin** [comment] 2021-03-24 08:56
Hi @thotheolh , thanks for reporting your issue.

This error is likely caused by your version of openssl. It must be 1.1.1e or later. Support for `EVP_PKEY_meth_get_digestsign` was incorporated into OpenSSL with this commit https://github.com/openssl/openssl/commit/2555285fa5e4248ad4a5a0bc14ae4606443856c2 back in November 2019, and appeared in release 1.1.1e and above.

Assuming that your are compiling on Linux, if you are using a recent distribution, check if you can update your RPMs or DEBs to a more recent release. If you can't, consider upgrading to a more recent distribution, or consider building with statically-compiled OpenSSL (instructions are provided in `docs/INSTALL.md`).

Please confirm the diagnostic on your version of OpenSSL. I'll file an enhancement to detect the version patch level at configure time.

Thanks!

**Comment by keldonin** [comment] 2021-03-26 08:11
Hi @thotheolh , have you been able to solve your problem?

Thanks,

**Comment by keldonin** [comment] 2021-04-04 02:25
Hello @thotheolh,

as I haven't received an answer back from you, I'm assuming your problem is solved. I'm closing this issue right now. If you still encounter problems, please reach out and I'll reopen the case.

Thanks,

**Closed by keldonin** 2021-04-04 02:25 UTC
Labels: enhancement, question
