### ISSUE TITLE
build failure on Linux

### ISSUE THREAD

**Issue by tulsidas** [Mastercard/pkcs11-tools#36] opened 2023-05-10 16:05 UTC
**Describe the bug**
Following the steps on INSTALL wiki, the `make` step fails to build the project

**To Reproduce**
1. Clone project
2. run `./bootstrap.sh`
3. run `make`

Error:
```
In file included from attribctx_lexer.c:49:
../gl/string.h:965:1: error: expected ‘,’ or ‘;’ before ‘_GL_ATTRIBUTE_MALLOC’
  965 | _GL_FUNCDECL_SYS (strdup, char *,
      | ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1655: libp11_la-attribctx_lexer.lo] Error 1
```
Attaching [config.log](https://github.com/Mastercard/pkcs11-tools/files/11444573/config.log)

**Operating System (please complete the following information):**
 - OS: `Linux desktop 6.1.0-8-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.25-1 (2023-04-22) x86_64 GNU/Linux`

**Comment by keldonin** [comment] 2023-05-12 09:05
Hi @tulsidas, I also encountered this issue on FreeBSD, when using recent versions of GCC. It seems to be caused by:
- `flex` that generates C code from lexer files, where the order of includes has `string.h` being included before `stdlib.h`
- `gnulib` that creates replacement header files, that implies this ordering
-  probably some other compiler-related cause that I haven't identified yet.

I could make it work by using clang as the compiler on my platform. Can you give it a try?

```
# I haven't checked, I would expect the package name to be clang, please verify how it's labelled
sudo apt-get install clang

./bootstrap.sh
./configure CC=clang
make
```

**Comment by tulsidas** [comment] 2023-05-12 12:21
@keldonin that worked! thanks for the quick response 👍🏼

**Comment by keldonin** [comment] 2023-05-12 12:53
@tulsidas you welcome. There is nevertheless an underlying issue that we must address.

**Comment by tulsidas** [comment] 2023-05-12 13:51
feel free to contact me if you need to try out something on Linux

**Comment by tulsidas** [comment] 2023-05-25 16:34
Yes, Debian _testing_ thou

```
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by keldonin** [comment] 2023-05-26 07:13
Hi @tulsidas, thanks for the information. I see this version will be released by June 10th. I'll give it a try - on a side note, the project compiles like a charm on the current Debian release (11).

**Comment by tulsidas** [comment] 2023-07-18 13:19
@keldonin FYI I just tried building today (a fresh clone) and it worked ok

**Closed** 2023-07-18 13:19 UTC
Labels: bug

**Comment by keldonin** [comment] 2023-07-18 14:09
> @keldonin FYI I just tried building today (a fresh clone) and it worked ok

As of release 2.6.0 I intend to ship binaries. There are already RPMs available, Debian packages to come later. You could try to deploy the RPM using `alien` on Ubuntu.
